version: '3.8'
networks:
  deploy-guide-dev:
    driver: bridge
services:
  app:
    container_name: deploy-guide
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - deploy-guide-dev
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: habit_user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: deploy-guid
    ports:
      - "5432:5432"
    networks:
      - deploy-guide-dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # порт для приложений
      - "15672:15672" # порт для панели управления
    networks:
      - deploy-guide-dev
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  postgres-data: