# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  app:
    build:
      context: "C:\\Users\\dante\\RiderProjects\\WebApplication1\\WebApplication1"
      dockerfile: "Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/WebApplication1.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "webapplication1:dev"
    ports: []
    volumes:
    - "C:\\Users\\dante\\RiderProjects\\WebApplication1\\WebApplication1:/app:rw"
    - "C:\\Users\\dante\\RiderProjects\\WebApplication1:/src:rw"
    - "C:\\Users\\dante\\.nuget\\packages:/root/.nuget/packages"
    working_dir: "/app"
